config/routes.rb
Rails.application.routes.draw do
  get "/about" , to:"pages#about"
  get "/contact" , to:"pages#contact"
  get "wish_card_info/:id", to: "wish_list#show_wish" , as: "wish_card_info"
  get "/make_a_wish", to:"wish_list#card"
  get "/new_wish" , to:"wish_list#new_wish"
  post "/wish_card_list" , to:"wish_list#card_list"
  root "wish_list#card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wish_list.rb
class WishList < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def ab
    end

    def contact
    end
end

app/controllers/wish_list_controller.rb
class WishListController < ApplicationController
    def card
        @wish_lists = WishList.all
    end

    def new_wish
        @wish_list = WishList.new
    end

    def card_list
        #準備寫進資料庫
       clean_params = params.require(:wish_list).permit(:title, :description)
        @wish_list = WishList.new(clean_params)
        if @wish_list.save
            redirect_to make_a_wish_path, notice: "成功新增許願卡"
        else
           render :new_wish
        end
       
    end
    def show_wish
        render html: params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WishSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <% if flash.any? %>
    <div><%= notice %></div>
    <div><%= alert %></div>
  <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>關於我們</h1>
<!-- <a href="/contact">關於</a> -->
<!-- <%= link_to "關於","/contact"%> -->
<!-- <%= link_to "關於",contact_path%> -->
<%= link_to "about", contact_path %>
<!-- =>通常會使用這種方式去寫之後在routes裡面的連結裡面用path+符號進行變更網址名稱而且他是個方法寫錯就錯了 -->
<!-- <%= link_to "關於","contact_url"%> 在需要分享連結網址給別人的時候需要用這種方式 -->

app/views/pages/contact.html.erb
<h1>聯絡我們</h1>
<!-- <a href="/about">聯絡</a> -->
<%= link_to "聯絡", about_path%>

app/views/pages/home.html.erb
<h1>首頁</h1>

app/views/wish_list/card.html.erb
<h1>許願卡、清單</h1>
<%= link_to "新增許願卡" , new_wish_path%>

<% @wish_lists.each do |wish_list| %>
<li>
<%= link_to wish_list.title, wish_card_info_path(wish_list.id) %>
</li>
<% end %>

app/views/wish_list/new_wish.html.erb
<h1>新增許願卡</h1>


<%= form_for @wish_list, url: "/wish_card_list" do |f| %> 
    <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
    <div>
    <%= f.label :description %>
    <%= f.text_area :description %> 
    </div>
    <%= f.submit%>
 <% end %>